### ISSUE TITLE
FlutterView is not blurred

### ISSUE THREAD

**Issue by ghost** [Dimezis/BlurView#103]
I recently used Flutter and Android hybrid development, and now there is a scene that needs to display a fuzzy view on the Android platform and blur the Flutter view, but unfortunately, he only blurs the AndroidView, such as ImageView, TextView and other controls, Flutter View no ideal job

FlutterView is a SurfaceView that provides a getBitmap() to get the Api for viewing screenshots. Can you provide an api for incoming bitmaps for BlurView?

**Comment by isMeiying** [comment]
The general situation is: there is an ImageView and a FlutterView in an interface, only the ImageView is blurred, and the part of the Flutter is blank.

**Comment by isMeiying** [comment]
Or is there a way to combine two Bitmaps and hand them to blurView for blurring.Real-time blur can be paused if needed.

I can provide screenshot bitmap of Screen and FlutterView, what should I do? This is very important, thank you

**Comment by Dimezis** [comment]
This operation will be terribly inefficient because `FlutterView.getBitmap` will allocate a new Bitmap each time to do this.
And your use-case is too specific, so I won't include it into the library.
If you really want to do this, and you don't need real-time blur, you can fork the library and implement it manually. Just take Renderscript blur and pass the bitmap to it. Then merge somehow with the main snapshot and draw it

**Comment by isMeiying** [comment]
Thanks, I now have a merged bitmap, can you provide an api that can be blurred by passing in a bitmap? I need the automatic movement matrix of blurView

**Comment by Dimezis** [comment]
How do you imagine this API? Again, your case is too specific, this API is not needed for the general use.
If you need to do it, just fork the lib and access the bitmap in the BlurView and do whatever you want

**Comment by isMeiying** [comment]
Ok, actually I think it turns out like this, I pass in a full screen screenshot and then let BlurView blur some areas for me
