### ISSUE TITLE
how to use it on listAdapter?

### ISSUE THREAD

**Issue by mohammadbahadori99** [Dimezis/BlurView#112]
i want to make my listAdapter's items blur.how can i do it?

**Comment by Dimezis** [comment]
The same way as the regular view. What's the problem exactly?

**Comment by mohammadbahadori99** [comment]
thank you, i remove setHasFixedTransformationMatrix(true) and my problem solved.cause when i make this fun true,it didn't make items blur in right way.
I have another question,if i want make my recycler's item have round corner, i should put them in cardView with cardBackgroundColor = "#00000000" and this will reduce performance.
I have a suggestion; add this ability that user can set backgroundColor and radious to BlurView

**Comment by mohammadbahadori99** [comment]
I'm interested in helping you in this.

**Comment by Dimezis** [comment]
You don't need a CardView for that, neither any special support from the BlurView side.
See https://github.com/Dimezis/BlurView/issues/37

**Comment by icarapovic** [comment]
I have a similar issue where I have a ViewHolder: ConstraintLayout (transparent, contains paddings), inside of it is a single CardView and inside of the CardView are other elements. I want the CardViews background to be blurred.

Where should I exactly put the BlurView? I presume I need to wrap the CardView in it? 

Also, when I use the ConstraintLayout as root (the root view of the viewholder), which is the closest parent, there is no blur applied as its transparent. The entire recyclerview and its children have no backgrounds, they lie in an activity that provides background. Unfortunately your example app blurs content outside of the recycler/scroll so I didn't help much.

**Comment by Dimezis** [comment]
@icarapovic can you please post a screenshot of an example of what you're trying to achieve?
I have a feeling that BlurView might not be the best tool for this, as it seems like you're blurring the static content, or maybe I just don't understand the requirement.

**Comment by icarapovic** [comment]
I cant post a screenshot because of an NDA.

Basically heres the view layering:
Activity (with background drawable)
Fragment (fullscreen, no bg)
RecyclerView (fullscreen, no bg)
Items in the recycler (blurred bg)

Since I need to draw items blur the activity is actually the only ViewGroup that has a backgeound that the lib need to draw the blur. Setting it up with the itemview, recycler or fragment would have no effect because they all have no bacgrounds to blur above. The pain was to pass the activity rootview that isn't transparent all the way to the viewholders to draw the blur.
