### ISSUE TITLE
When I use bottomMenuBar(Blur View) as fragment selector,it can not switch fragment centent automatically.

### ISSUE THREAD

**Issue by ShineYang** [Dimezis/BlurView#12]
****for more information,here is my email:shineyang@shineyang.com.

page1
<img src="http://i4.piimg.com/4851/cfdf1761e73567aa.png">

page2
<img src="http://i4.piimg.com/4851/10f13cc6ff267f19.png">

page3
<img src="http://i4.piimg.com/4851/98f79e6e849f9920.png">

**Comment by Dimezis** [comment]
Please describe how are you switching between fragments.
Is the problem persists if all the fragments have content (different from transparent background)?

**Comment by ShineYang** [comment]
I use " fragmentTransaction.hide(from).add(R.id.frag_content, to).commit()" to switch the fragment content.
If all the fragments have content,problem persists but the blurView background will changed after a short delay.

**Comment by Dimezis** [comment]
Can you please send the source of this example project?

**Comment by Dimezis** [comment]
I can assume that you are setting wrong root layout in `blurView.setupWith(View)` method.
Wasn't able to reproduce with the android.R.id.content as a root layout. 

But the problem persists (which is natural) if you set it up with the Fragment1 root layout.

**Comment by ShineYang** [comment]
Here is the demo url https://github.com/ShineYang/TestBottomBlurMenu

**Comment by Dimezis** [comment]
Ok, so I've found the problem. I'm not sure if I can fix it, but as a quick workaround you can swap these lines:
```
changeQuickMenu();
switchContent(mfrom, fragment1);
```
 to be
```
switchContent(mfrom, fragment1);
changeQuickMenu();
```
and so on for other tab items.

As an alternative, you can add fragment transition animation which will also trigger blur update.

It happens because `changeQuickMenu` triggers BlurView's redraw and it stops its blur update when it's drawing itself. 
And because fragment transaction is also processed in message queue, it delays that notification about BlurView's draw ending.

**Comment by ShineYang** [comment]
Bingo! It works for me, just like what you described in the answer,**the fragment transaction is also processed in message queue, it delays that message about BlurView's draw ending**.
Thank you! Your help was greatly appreciated.
