### ISSUE TITLE
Have you considered to add Vulkan or google's toolkit implementation?

### ISSUE THREAD

**Issue by Danubis-Luo** [Dimezis/BlurView#198]
For devices under Android 31, google recommends using their toolkit or Vulkan to replace depreciated RenderScript for better performance. Have you considered to add those implementations to your library?

**Comment by Dimezis** [comment]
There's a RenderEffectBlur to replace RenderscriptBlur on newer APIs. Hope that works for you.

It's way simpler than the Vulkan or OpenGL approach, so I'm not really considering them

**Comment by Danubis-Luo** [comment]
But RenderEffect does not work on devices under Android 31.

**Comment by Dimezis** [comment]
Ah, by "under" you meant before Android 31.
No, I'm not planning anything. I don't think it's worth the effort

**Comment by Dimezis** [comment]
The Toolkit could be integrated more or less painlessly, but there are still a couple of problems with it.
1) It [allocates](https://github.com/android/renderscript-intrinsics-replacement-toolkit/blob/main/renderscript-toolkit/src/main/java/com/google/android/renderscript/Toolkit.kt#L236) a bitmap on each blur call, which is not good, but could be avoided easily if forked
2) It's not clear if it's actually better than Renderscript, since it's also executed on the CPU. With Renderscript, there's at least a chance that a given device might still have RS GPU support. The Toolkit always runs on CPU though, so there's no good way to guess what algorithm would be faster on any particular device.
