### ISSUE TITLE
Drawing whats beneath layout

### ISSUE THREAD

**Issue by mhgk** [Dimezis/BlurView#20]
Hey guys.
Maybe its a blunder from my part, but is it possible to blur extacly what is beneath a view.
Right now i can only blur the entire underlaying view, and not the area covered by me BlurView.

Thx.

**Comment by Dimezis** [comment]
Hey.

I'm a bit confused... 
Maybe I got you wrong but it actually blurs the exact area beneath the BlurView.

Yes, we ask to blur the entire View beneath the BlurView, but what happens internally is:
BlurView creates the bitmap with same size as itself (downscaled, but it doesn't matter).
It requests the underlying view to draw itself on this bitmap, and it draws only as much, as BlurView takes place. 
Then, this small bitmap is blurred. 

Is that what you asked? Or you would like to pass some kind of Rectangle to blur on its position instead of View?

**Comment by mhgk** [comment]
hehe communication :D

I have fragment, which have a blurView (200dp x 200dp). I want the blurView to blur only the 200x200 of what it covers from the underlaying screen.

Does it make sense?

**Comment by Dimezis** [comment]
I guess it's possible, why not? 
If you have some examples, show the code, maybe I'll notice something.

**Comment by Dimezis** [comment]
Hmm, there is a problem actually. 
View is in 0x0 position relative to its fragment, so it blurs the content in that position.
I don't think it can be fixed. Don't use fragment for that purpose.

**Comment by Dimezis** [comment]
Actually, It was fixed in 1.3.0 version.
Sorry it took so long.
Now it is possible to calculate BlurView's position relative to root view that you pass during set up, which solves this kind of problems.
