### ISSUE TITLE
Disable blur for certain views

### ISSUE THREAD

**Issue by FelipeRRM** [Dimezis/BlurView#29]
Hey there, great lib by the way.

Is there a way to disable the blur just for a view? Thing is I have a textView which animates from the center of the screen over to the blurview, but as it is outside the blurLayout, it gets blurred, and as it is animating, it gets really slow!

**Comment by Dimezis** [comment]
Hey.

Currently there's no way to do it directly, because it's not me traversing the views hierarchy, it's root view.

But, you can try to put in a different parent layout.
So make `setupWith` with some ViewGroup with all the content you need, and put your animated TextView in some other one, which will not be a child of your rootView

**Comment by FelipeRRM** [comment]
Wow, it worked! Thank you very much for that!
