### ISSUE TITLE
NullPointExpection

### ISSUE THREAD

**Issue by Kuki93** [Dimezis/BlurView#99]
BlurController  -> onPreDraw -> updateBlur ->    rootView.draw(internalCanvas);
internalCanvas is null

**Comment by Dimezis** [comment]
Post the full stacktrace, your setup and when it's happening

**Comment by Kuki93** [comment]
sorry,I don't know how to reproduce it.


1 android.view.View.drawBackground(View.java:19506)
2 android.view.View.draw(View.java:19305)
3 eightbitlab.com.blurview.a.a(BlockingBlurController.java:144)
4 eightbitlab.com.blurview.a$1.onPreDraw(BlockingBlurController.java:59)
5 android.view.ViewTreeObserver.dispatchOnPreDraw(ViewTreeObserver.java:977)
6 android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2516)
7 android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1515)
8 android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7266)
9 android.view.Choreographer$CallbackRecord.run(Choreographer.java:981)
10 android.view.Choreographer.doCallbacks(Choreographer.java:790)
11 android.view.Choreographer.doFrame(Choreographer.java:721)
12 android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:967)
13 android.os.Handler.handleCallback(Handler.java:808)
14 android.os.Handler.dispatchMessage(Handler.java:101)
15 android.os.Looper.loop(Looper.java:166)
16 android.app.ActivityThread.main(ActivityThread.java:7529)
17 java.lang.reflect.Method.invoke(Native Method)
18 com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:245)
19 com.android.internal.os.ZygoteInit.main(ZygoteInit.java:921)

**Comment by Dimezis** [comment]
That's not a full stacktrace, I don't see a crash in it, and it points to `View`

**Comment by Kuki93** [comment]
please,

java.lang.NullPointerException
Attempt to invoke virtual method 'boolean android.graphics.Canvas.isHardwareAccelerated()' on a null object reference

1 android.view.View.drawBackground(View.java:20653)
2 android.view.View.draw(View.java:20454)
3 eightbitlab.com.blurview.e.b(BlockingBlurController.java:144)
4 eightbitlab.com.blurview.a.onPreDraw(BlockingBlurController.java:59)
5 android.view.ViewTreeObserver.dispatchOnPreDraw(ViewTreeObserver.java:993)
6 android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2695)
7 android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1628)
8 android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7917)
9 android.view.Choreographer$CallbackRecord.run(Choreographer.java:1092)
10 android.view.Choreographer.doCallbacks(Choreographer.java:893)
11 android.view.Choreographer.doFrame(Choreographer.java:812)
12 android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1078)
13 android.os.Handler.handleCallback(Handler.java:891)
14 android.os.Handler.dispatchMessage(Handler.java:102)
15 android.os.Looper.loop(Looper.java:207)
16 android.app.ActivityThread.main(ActivityThread.java:7539)
17 java.lang.reflect.Method.invoke(Native Method)
18 com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
19 com.android.internal.os.ZygoteInit.main(ZygoteInit.java:958)

**Comment by Kuki93** [comment]
-_-。sorry！Can you solve it?

**Comment by Dimezis** [comment]
Can you at least post your setup, layout, android version, etc?

**Comment by ChristopherDuran** [comment]
Just i want to blur a layout, not more, what i am doing bad?, i`m coding that: 

XML:
<?xml version="1.0" encoding="utf-8"?>
<RelativeLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    tools:context=".SignOutConfirm">

    <eightbitlab.com.blurview.BlurView
        android:id="@+id/BlurViewX"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        app:blurOverlayColor="@color/colorPrimary"
        >
        <RelativeLayout
            android:id="@+id/RL"
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            android:layout_gravity="center">
            <TextView
                android:text="Que onda"
                android:id="@+id/Textx"
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                android:textSize="55dp"
                android:layout_gravity="center"/>
        </RelativeLayout>
    </eightbitlab.com.blurview.BlurView>
</RelativeLayout>


This is my Java file:
package com.christech.divespot.divespot;

import android.graphics.drawable.Drawable;
import android.support.v7.app.AppCompatActivity;
import android.os.Bundle;
import android.view.View;
import android.view.ViewGroup;

import eightbitlab.com.blurview.BlurView;
import eightbitlab.com.blurview.RenderScriptBlur;


public class SignOutConfirm extends AppCompatActivity {

    float radius = 20f;
    BlurView bottomblurView;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_sign_out_confirm);

        View decorView = getWindow().getDecorView();
        ViewGroup rootView = (ViewGroup)decorView.findViewById(R.id.BlurViewX);
        Drawable windowBackground = decorView.getBackground();

        bottomblurView.setupWith(rootView).setFrameClearDrawable(windowBackground).
                setBlurAlgorithm(new RenderScriptBlur(this)).
                setBlurRadius(radius).setHasFixedTransformationMatrix(true);
    }
}






This is my error:
__

- 08-05 05:41:22.549 11343-11343/com.christech.divespot.divespot E/AndroidRuntime: FATAL EXCEPTION: main
-     Process: com.christech.divespot.divespot, PID: 11343
-     java.lang.RuntimeException: Unable to start activity ComponentInfo{com.christech.divespot.divespot/com.christech.divespot.divespot.SignOutConfirm}: java.lang.NullPointerException: Attempt to invoke virtual method 'eightbitlab.com.blurview.BlurViewFacade eightbitlab.com.blurview.BlurView.setupWith(android.view.ViewGroup)' on a null object reference
-         at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2416)
-         at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476)
-         at android.app.ActivityThread.-wrap11(ActivityThread.java)
-         at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344)
-         at android.os.Handler.dispatchMessage(Handler.java:102)
-         at android.os.Looper.loop(Looper.java:148)
-         at android.app.ActivityThread.main(ActivityThread.java:5417)
-         at java.lang.reflect.Method.invoke(Native Method)
-         at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
-         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
-      Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'eightbitlab.com.blurview.BlurViewFacade eightbitlab.com.blurview.BlurView.setupWith(android.view.ViewGroup)' on a null object reference
-         at com.christech.divespot.divespot.SignOutConfirm.onCreate(SignOutConfirm.java:27)
-         at android.app.Activity.performCreate(Activity.java:6237)
-         at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1107)
-         at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2369)
-         at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476) 
-         at android.app.ActivityThread.-wrap11(ActivityThread.java) 
-         at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344) 
-         at android.os.Handler.dispatchMessage(Handler.java:102) 
-         at android.os.Looper.loop(Looper.java:148) 
-         at android.app.ActivityThread.main(ActivityThread.java:5417) 
-         at java.lang.reflect.Method.invoke(Native Method) 
-         at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) 
-         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)_

And i can apply Blur to Fragments?, thannks for your response, this library is amazing

**Comment by Dimezis** [comment]
@ChristopherDuran `bottomblurView = findViewById(R.id.BlurViewX)`.
Also `rootView` must not be a BlurView.

Please don't post irrelevant issues and follow example project.

**Comment by ChristopherDuran** [comment]
> @ChristopherDuran `bottomblurView = findViewById(R.id.BlurViewX)`.
> Also `rootView` must not be a BlurView.
> 
> Please don't post irrelevant issues and follow example project.

okey i`m sorry just for know what could be happened with the Null P Exception
